"""Conversation states for the bot conversation handlers."""

# Define all conversation states in one place
(SELECTING_TOPIC, FENG_SHUI_ASSESSMENT, MBTI_ASSESSMENT, 
 I_CHING_ASSESSMENT, BA_ZI_ASSESSMENT, ZI_WEI_ASSESSMENT,
 FENG_SHUI_ROOM, FENG_SHUI_DIRECTIONS,
 MBTI_QUESTION_1, MBTI_QUESTION_2, MBTI_QUESTION_3, MBTI_QUESTION_4,
 I_CHING_QUESTION, BA_ZI_BIRTHDATE, ZI_WEI_BIRTHDATE, ZI_WEI_BIRTHTIME) = range(16)